"""Subclass of frm_home, which is generated by wxFormBuilder."""

import wx
import Main

# Implementing frm_home
class DDL_creater_projectfrm_home( Main.frm_home ):
	def __init__( self, parent ):
		Main.frm_home.__init__( self, parent )
	
