"""Subclass of frm_home, which is generated by wxFormBuilder."""

import wx
import ddl

# Implementing frm_home
class DDL_creater_projectfrm_home( ddl.frm_home ):
	def __init__( self, parent ):
		ddl.frm_home.__init__( self, parent )
	
	# Handlers for frm_home events.
	def filePicker_xmlfileOnFileChanged( self, event ):
		# TODO: Implement filePicker_xmlfileOnFileChanged
		pass
	
	def dirPicker_DDLfilesOnDirChanged( self, event ):
		# TODO: Implement dirPicker_DDLfilesOnDirChanged
		pass
	
	def button_generateOnButtonClick( self, event ):
		# TODO: Implement button_generateOnButtonClick
		pass
	
	def button_cancelOnButtonClick( self, event ):
		# TODO: Implement button_cancelOnButtonClick
		pass
	
	
