"""Subclass of msg_somethigWrong, which is generated by wxFormBuilder."""

import wx
# import Validations

# Implementing msg_somethigWrong
# class msg_somethigWrong(msg_somethigWrong):
# 	def __init__(self, parent,
# 				 msg=u'\n\nsomething went wrong while loading data into SQLite, \nplease check your input data'):
# 		Validations.msg_somethigWrong.__init__(self, parent, msg)

	# Handlers for msg_somethigWrong events.
	# def btn_okOnButtonClick(self, event):
	# 	self.Destroy()

class msg_somethigWrong(wx.Dialog):
	def __init__(self, parent, msg=u'\n\nsomething went wrong while loading data into SQLite, \nplease check your input data'):
		wx.Dialog.__init__(self, parent, id=1019, title=u"Sorry: something went wrong ", pos=wx.DefaultPosition,
						   size=wx.Size(458, 212), style=wx.DEFAULT_DIALOG_STYLE)

		self.SetSizeHintsSz(wx.DefaultSize, wx.DefaultSize)

		bSizer1 = wx.BoxSizer(wx.VERTICAL)

		self.m_staticText1 = wx.StaticText(self, wx.ID_ANY, msg, wx.DefaultPosition, wx.DefaultSize, 0)
		self.m_staticText1.Wrap(-1)
		bSizer1.Add(self.m_staticText1, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL, 5)

		gSizer1 = wx.GridSizer(1, 1, 0, 0)

		self.btn_ok = wx.Button(self, 1020, u"OK", wx.DefaultPosition, wx.DefaultSize, 0)
		gSizer1.Add(self.btn_ok, 0, wx.ALL | wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 5)

		bSizer1.Add(gSizer1, 1, wx.EXPAND, 5)

		self.SetSizer(bSizer1)
		self.Layout()

		self.Centre(wx.BOTH)

		# Connect Events
		self.btn_ok.Bind(wx.EVT_BUTTON, self.btn_okOnButtonClick)

	def __del__(self):
		pass

	# Virtual event handlers, overide them in your derived class
	def btn_okOnButtonClick(self, event):
		self.Destroy()
	def setMsg(self, msg):
		self.m_staticText1.SetLabel(msg)